on:
  push:
    branches:
      - main

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      TRANSLATION_KEY: ${{ secrets.AZURE_COGNITIVE_SERVICE_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - run: dotnet tool update -g docfx
    - run: dotnet tool install DocLanguageTranslator -g

    - run: DocLanguageTranslator -d ./ -k $TRANSLATION_KEY
    - run: docfx ./docfx.json

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './_site'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
